services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - webnet
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ~/BARAKOD/song-app-uploads:/app/server/uploads
      - ~/BARAKOD/song-app-data:/app/server/data
    environment:
      - BIND_ADDRESS=0.0.0.0
      - UPLOADS_DIR=/app/server/uploads
      - DB_PATH=/app/server/data/songs.db
      - NODE_ENV=production
    networks:
      - webnet

networks:
  webnet:
    driver: bridge